#KPI 1 WEEKDAY VS WEEKEND FLIGHTS
select count(FLIGHT_NUMBER) from flights22;
select weeK_name, concat(round(count(FLIGHT_NUMBER)/1048575*100, 2),"%") as NO_OF_FLIGHTS
from flights22
group by weeK_name;

#KPI 2 FLIGHTS CANCELLED FOR JETBLUE AIRLINES ON FIRST 1ST DAY OF EVERY MONTH
select MONTH AS MONTH_NUMBER,SUM(CANCELLED) AS TOTAL_CANCELLED FROM flights22
JOIN airlines ON flights22.AIRLINE=airlines.IATA_CODE
WHERE DAY IN (1) AND airlines.AIRLINE IN("JetBlue Airways")
GROUP BY MONTH;

# KPI 3 WEEK WISE FLIGHT DELAY STATISTICS
SELECT weeK_name,SUM(TOTAL_DELAY) TOTAL_DELAY FROM flights22 
group by weeK_name;

#KPI 4 STATE  WISE FLIGHT DELAY STATISTICS
SELECT STATE, SUM(TOTAL_DELAY) AS TOTAL_DELAY FROM airports
JOIN flights22 ON airports.IATA_CODE = flights22.ORIGIN_AIRPORT
group by STATE;

#KPI 5 CITY WISE FLIGHT DELAY STATISTICS
SELECT CITY, SUM(TOTAL_DELAY) FROM airports
JOIN flights22 ON airports.IATA_CODE = flights22.ORIGIN_AIRPORT
group by CITY;
# KPI 6 WEEK,STATE & CITY WISE FLIGHT DELAY STATISTICS
SELECT weeK_name,STATE,CITY, SUM(TOTAL_DELAY) AS TOTAL_DELAY FROM airports
JOIN flights22 ON airports.IATA_CODE = flights22.ORIGIN_AIRPORT
group by weeK_name,STATE,CITY
ORDER BY SUM(TOTAL_DELAY) DESC;
#kpi 7 STATE WISE TOTAL AIRPORTS
select state, count(AIRPORT) as Total_airports from airports
group by state order by count(AIRPORT) desc;

#kpi 8 CITY WISE TOTAL AIRPORTS
select city, count(AIRPORT) as Total_airports from airports
group by city order by count(AIRPORT)  desc;
#KPI 9 Total_airlines, TOTAL_AIRPORTS, NO_OF_FLIGHTS, TOTAL_DISTANCE, AND TOTAL_DELAY STATISTICS 
SELECT COUNT(distinct airline) Total_airlines,
COUNT( DISTINCT AIRPORT) AS TOTAL_AIRPORTS,
COUNT( DISTINCT FLIGHT_NUMBER) AS NO_OF_FLIGHTS_DISTINCT,
COUNT(  FLIGHT_NUMBER) AS NO_OF_FLIGHTS_ALL,
SUM(DISTANCE) AS TOTAL_DISTANCE,
sum(TOTAL_DELAY) as TOTAL_DELAY from flights22 
 LEFT JOIN airports ON flights22.ORIGIN_AIRPORT = airports.IATA_CODE;
#KPI 10 AIRLINE WISE TOTAL DELAY
 SELECT airlines.AIRLINE as AIRLINE, sum(TOTAL_DELAY) as TOTAL_DELAY from airlines
 left join flights22 on airlines.IATA_CODE=flights22 .AIRLINE
 group by AIRLINE;
 #KPI 11 AIRLINE WISE NO_OF FLIGHTS
 SELECT airlines.AIRLINE as AIRLINE, COUNT( DISTINCT FLIGHT_NUMBER ) as NO_OF_FLIGHTS from airlines
 left join flights22 on airlines.IATA_CODE=flights22 .AIRLINE
 group by AIRLINE order by COUNT(distinct FLIGHT_NUMBER ) DESC;

select*from flights22;
select TOTAL_DELAY, case when TOTAL_DELAY <= "00:00:00" then "NO DELAY"
ELSE "DELAY" END AS "DELAY_OR_No_DELAY" FROM flights22;
ALTER TABLE flights22 
ADD COLUMN DELAY_OR_NO_DELAY VARCHAR(30);
UPDATE flights22  
SET DELAY_OR_NO_DELAY= case when TOTAL_DELAY <= "00:00:00" then "NO DELAY"
ELSE "DELAY"  END;
SET SQL_SAFE_UPDATES=0;
SELECT*FROM FLIGHTS22;
SELECT COUNT(DELAY_OR_NO_DELAY) FROM FLIGHTS22;
SELECT* FROM FLIGHTS22;
#KPI 12 NUMBERE OF FLIGHTS WITH NO TOTAL DELAY
SELECT airlines.AIRLINE , COUNT(FLIGHT_NUMBER) AS TOTAL_FLIGHTS,SUM(TOTAL_DELAY) AS DELAY FROM airlines
LEFT JOIN flights22 ON airlines.IATA_CODE=FLIGHTS22.AIRLINE
WHERE DELAY_OR_NO_DELAY IN ("NO DELAY") AND DISTANCE BETWEEN 2500 AND 3000
GROUP BY airlines.AIRLINE ORDER BY TOTAL_FLIGHTS DESC;

#KPI 13 NUMBERE OF FLIGHTS WITH NO DEPARTURE_DELAY AND ARRIVAL_DELAY
SELECT airlines.AIRLINE , COUNT( FLIGHT_NUMBER) AS TOTAL_FLIGHTS,SUM(TOTAL_DELAY) AS NO_DEP_AND_ARIVL_DELAY FROM airlines
LEFT JOIN flights22 ON airlines.IATA_CODE=FLIGHTS22.AIRLINE
WHERE DEPARTURE_DELAY <= "00:00:00" AND ARRIVAL_DELAY <= "00:00:00"  AND DISTANCE BETWEEN 2500 AND 3000
GROUP BY airlines.AIRLINE ORDER BY TOTAL_FLIGHTS DESC;




 
 
 






